version: '3'
services:
  db:
    image: mariadb:10.2
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  app:
    image: netsoc-website/app
    build:
      context: ./build
    restart: on-failure
    links:
      - db
    volumes:
      - ./app:/opt/app:ro
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_SECRET=${FLASK_SECRET}
      - PUBLIC_HOST=${PUBLIC_HOST}
      - HTTP_PORT=${HTTP_PORT}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=whatevs
    ports:
      - "$HTTP_PORT:8080"

volumes:
  db_data:
